name: Django App CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
      name: Test
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start docker images
        run: |
          DOCKER_BUILDKIT=1  docker-compose build --no-cache
          sudo chmod +x start_services.sh
          ./start_services.sh
        shell: bash


 



  deploy:
    # needs: build
    name: Deploy to Elasticbeanstalk
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Set Pulumi Environment Variables
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          echo "PULUMI_ACCESS_TOKEN=$PULUMI_ACCESS_TOKEN" >> $GITHUB_ENV
      
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Run Pulumi up
        env:
          USERNAME: ${{ secrets.DB_USER }}
          PASSWORD: ${{ secrets.DB_PASS }}
        run: |
          curl -fsSL https://get.pulumi.com | sh
          cd ./infrastructure-aws
          pip install -r requirements.txt
          pulumi stack select sja/infrastructure-aws/dev
          pulumi config set --secret db_password $DB_USER
          pulumi config set --secret db_password $DB_PASS
          pulumi up --yes


      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Generate Deployment Package
        run: zip -r deploy.zip * 


      - name: Deploy to Test Env
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: django-app 
          environment_name: dev-env-8178e24
          version_label: "harverstalert-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip