name: Django App CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     test:
      name: Test
      #Run on Ubuntu using the latest version
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start docker images
        run: |
          DOCKER_BUILDKIT=1  docker-compose build --no-cache
          sudo chmod +x start_services.sh
          ./start_services.sh
        shell: bash


  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: [3.7, 3.9]

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: djangoCon_app
          IMAGE_TAG: latest
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG